### ISSUE TITLE
Avoid dot imports

### ISSUE THREAD

**Issue by is2ei** [nulab/go-typetalk#38]
Can we consider to avoid dot imports? 

e.g.

```
. "github.com/nulab/go-typetalk/typetalk/internal"
. "github.com/nulab/go-typetalk/typetalk/shared"
```

It seems "dot imports" is not recommended.

https://golang.org/doc/effective_go.html
> (Don't use the import . notation, which can simplify tests that must run outside the package they are testing, but should otherwise be avoided.) 

https://github.com/golang/lint/issues/179
> Are dot imports evil?

It would be change in its structure if we try to avoid the "dot imports". I'd like to discuss it first.

**Comment by vvatanabe** [comment]
@is2ei 
Yes, it is not recommended. It's my negligence in the past. Should quit the dot import ASAP.

**Comment by is2ei** [comment]
Thanks for your response!
I see. I'd create PR then.
