### ISSUE TITLE
Support go modules

### ISSUE THREAD

**Issue by vibridi** [nulab/go-typetalk#53]
I would like to upgrade this library to use go modules (and in the meantime upgrade to go 1.13).
To support go modules, ~~being on `v1` we'll have to move to `v2` and decide whether to drop backwards compatibility or not~~
It looks like you already have some package versioning. I'm not sure how you guys use it though, because there's up to `v5` package but the latest release tag is `v2.1.0`

**Comment by is2ei** [comment]
> there's up to v5 package but the latest release tag is v2.1.0
v5 means it contains codes for Typetalk API v5

**Comment by vibridi** [comment]
Ok, I'm going to fork this and open a PR first

**Comment by vibridi** [comment]
@vvatanabe @is2ei So there's is a problem with supporting gomodules here.
The module name needs to be package-versioned, so the first line of `go.mod` file should be: `module github.com/vibridi/go-typetalk/v3` (because the latest release tag is in `v2`)

However the package `github.com/vibridi/go-typetalk/v3` already exists, and it's the client for typetalk api v3. 

So to support go modules, it looks like it's necessary to completely refactor the current directory structure. And then package `github.com/vibridi/go-typetalk/v3` will not have the same meaning it has today.

Thoughts?

**Comment by vibridi** [comment]
Also I'm not sure how exactly the api is supposed to be used. 
It looks like different version clients can coexist in the same program. Is this actually the case? 

For example, `ReadNotification` and `GetNotificationCount` are in different api versions, so what if my program needs both of them? Do I need to do this?
```
import (
	"github.com/nulab/go-typetalk/typetalk/v3"
	"github.com/nulab/go-typetalk/typetalk/v5"
)

func main() {
	clientv3 := v3.NewClient(http.DefaultClient)
	clientv3.Notifications.ReadNotification(...)

	clientv5 := v5.NewClient(http.DefaultClient)
	clientv5.Notifications.GetNotificationCount(...)
}
```

**Comment by is2ei** [comment]
@vibridi 

> However the package github.com/vibridi/go-typetalk/v3 already exists,
No 😓 

In README, this is noted.
`import "github.com/nulab/go-typetalk/typetalk/v3"`

So, it might be:
`import "github.com/vibridi/go-typetalk/typetalk/v3"`

> so what if my program needs both of them? Do I need to do this?
Yes.
