### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by is2ei** [nulab/go-typetalk#64]
## References
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg
https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com

**Comment by vvatanabe** [comment]
We will migrate GitHub Action.
https://github.com/nulab/go-typetalk/issues/85
