### ISSUE TITLE
Remove the code that drains the response body

### ISSUE THREAD

**Issue by vvatanabe** [nulab/go-typetalk#9]
It has already been fixed in the Golang 1.7+.
refs: https://github.com/google/go-github/pull/317

**Comment by ehyyoj** [comment]
hi, I'm try to figure out the HTTP connections reuse. 
After I saw the docs, it seems still need to drain `response.Body` now.
https://github.com/golang/go/commit/246e6ceb3bdbcfdb9f562c67622c3d67a45eb70d
